### ISSUE TITLE
Is there a way to filter log by context AND filter?

### ISSUE THREAD

**Issue by mcicak** [regexident/DLLog#1]
For example, I want to filter logs for level Warning (and above) and given contexts. But after:

```
DLLogBeginContextObservation(@[ ctx1, ctx2 ]);
DLLogPushLevelFilter(DLLogLevelWarning);
```

only context filter is applied. I'm seeing ctx1 Info messages, and only want Warnings and above.

**Comment by mcicak** [comment]
I modified DLLog.m, line 132 to:

```
if (([dl_logContextSet containsObject:DLLogAnyContext()] || [dl_logContextSet containsObject:context]) && DLLogLevel##level <= DLLogGetLevelFilter()) { \
```

The key is to add level check condition:

```
(...) && DLLogLevel##level <= DLLogGetLevelFilter()
```

**Comment by regexident** [comment]
Fixed, thanks! commit (https://github.com/regexident/DLLog/commit/1d87fc14be1f3295912129468b12948eb8d8e8fa) :smiley:

**Comment by mcicak** [comment]
It is not enough to just add level check condition. OR condition needs to be in 'brackets' as well.

**Comment by regexident** [comment]
Please feel free to make a PR. :wink:
